apiVersion: apps/v1
kind: Deployment
metadata:
  name: qicoo-api
spec:
  replicas: 2
  template:
    spec:
      # initContainers:
      # - name: wait-for-qicoo-redis
      #   envFrom:
      #   - secretRef:
      #       name: qicoo-api-secret-staging
      # - name: wait-for-qicoo-mysql
      #   envFrom:
      #   - secretRef:
      #       name: qicoo-api-secret-staging
      containers:
      - name: qicoo-api
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 200m
        envFrom:
        - secretRef:
            name: qicoo-api-secret-staging
        - configMapRef:
            name: qicoo-api-configmap-staging
