namespace: production
commonLabels:
  variant: production
commonAnnotations:
  note: production
bases:
- ../../base
resources:
- qicoo-api-namespace.yaml
patches:
- qicoo-api-service.yaml
# TODO: USE AWS Secret Manager
secretGenerator:
- name: qicoo-mysql-secret
  envCommand: echo MYSQL_ROOT_PASSWORD=my-secret-pw
  type: Opaque
  behavior: replace