apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.qicoo.tokyo
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:297295734308:certificate/8a2b8c2c-7753-4ce0-8215-32ffb7711c58
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    app: qicoo-api
  name: qicoo-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 443
    targetPort: 8080
  selector:
    app: qicoo-api