apiVersion: v1
kind: ConfigMap
metadata:
  name: qicoo-api-configmap
data:
  DB_URL: "qicoo-mysql:3306"
  DB_USER: "root"
  REDIS_URL: "qicoo-redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: qicoo-api
  labels:
    app: qicoo-api
spec:
  selector:
    app: qicoo-api
  type: NodePort
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qicoo-api
spec:
  selector:
    matchLabels:
      app: qicoo-api
  replicas: 1
  template:
    metadata:
      labels:
        app: qicoo-api
    spec:
      initContainers:
      - name: wait-for-qicoo-redis
        image: redis:4.0.10
        command: ['/bin/sh', '-c']
        args: ['until redis-cli -h $qicoo-redis ping; do echo waiting for redis; sleep 2; done;']
      initContainers:
      - name: wait-for-qicoo-mysql
        image: mysql:5.6.27
        command: ['/bin/sh', '-c']
        args: ['until mysqladmin ping -hqicoo-mysql -uroot -p$DB_PASSWORD; do echo waiting for mysqldb; sleep 2; done;']
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qicoo-mysql-secret
              key: MYSQL_ROOT_PASSWORD
      containers:
      - name: qicoo-api
        image: cndjp/qicoo-api:v0.0.1
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: qicoo-api-configmap
                key: DB_URL
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: qicoo-api-configmap
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: qicoo-mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: qicoo-api-configmap
                key: REDIS_URL
        # # Health check
        # readinessProbe:
        #   httpGet:
        #     path: /v1/jkd1812/questions?start=1&end=10&sort=created_at&order=desc
        #     port: http
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /v1/jkd1812/questions?start=1&end=10&sort=created_at&order=desc
        #     port: http
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        imagePullPolicy: Always