apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchlabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: master
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
      restartPolicy: Always
